// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerAPI.Data;

#nullable disable

namespace ServerAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220120182042_SkillsData")]
    partial class SkillsData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Core.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "This is a description of category 1",
                            Name = "Category 1",
                            ThumbnailPath = "uploads/placeholder.jpg"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "This is a description of category 2",
                            Name = "Category 2",
                            ThumbnailPath = "uploads/placeholder.jpg"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "This is a description of category 3",
                            Name = "Category 3",
                            ThumbnailPath = "uploads/placeholder.jpg"
                        });
                });

            modelBuilder.Entity("Core.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = -1,
                            Description = "C# is my primary programming language. I've been using this language since 2009 to build Windows Services, WPF Applications, Web applications (WebForms, MVC, WebAPI, SOAP Services), and Console utilities for the companies I have worked for. I find C# to be extremely flexible with excellent tooling and support built around it.",
                            DisplayOrder = 1,
                            ImagePath = "assets/img/CSharp.png",
                            Title = "C# Development"
                        },
                        new
                        {
                            SkillId = -2,
                            Description = "I am familiar with some of the more popular web technologies, HTML 5, Bootstrap, Javascript/jQuery, along with some less well known items like pico.css. I hope to expand into Angular, React, and Vue as time allows.",
                            DisplayOrder = 2,
                            ImagePath = "assets/img/CoreWebTech.png",
                            Title = "Core Web Technologies"
                        },
                        new
                        {
                            SkillId = -3,
                            Description = "As part of honing my skills, this site is an experiment and learning experience building web applications with Blazor and WebASM technologies. This gives me a chance to try out new things and build more progressive web applications with better UX.",
                            DisplayOrder = 3,
                            ImagePath = "assets/img/ASPNetBlazor.png",
                            Title = "Blazor"
                        },
                        new
                        {
                            SkillId = -4,
                            Description = "Over my career I have spend a significant time writing SQL. This varied from stored procedures for application logic, maintenance, diagnostics, and even CLR extended functions to enhance functionality. I'm no stranger to EF code or database first either! ",
                            DisplayOrder = 4,
                            ImagePath = "assets/img/SQLDatabase.png",
                            Title = "Database Development"
                        },
                        new
                        {
                            SkillId = -5,
                            Description = "I have some experience with maintaining server infrastructure both on premises and in the cloud. I've also started to learn Azure deployment with CI/CD with this project utilising Github actions to automate the deployment process. ",
                            DisplayOrder = 5,
                            ImagePath = "assets/img/Azure.png",
                            Title = "Devops"
                        },
                        new
                        {
                            SkillId = -6,
                            Description = "I've been teaching myself the Python language using the Django framework as part of a hobby project. Learning new skills and languages is both a fun challenge and important to my continual impovement for my career; plus it allows me to pivot when needed.",
                            DisplayOrder = 6,
                            ImagePath = "assets/img/python.svg",
                            Title = "Python + Django"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
